# from tkinter import *
# parent = Tk()
# parent.title("Welcome")
# parent.geometry("600x300")
# name = Label(parent,text = "Name:")
# name.grid(row=0,column=0,pady=10,padx=5)
# e1 = Entry(parent)
# e1.grid(row = 0, column = 1)
# password = Label(parent,text = "Password:")
# password.grid(row=1,column=0,pady=10,padx=5)
# e2 = Entry(parent)
# e2.grid(row = 1,column = 1)
# btn1 = Button(parent,text="Submit")
# btn1.grid(row = 3, column = 1)
# parent.mainloop()

from tkinter import *
window = Tk()
window.title("Hello")
window.geometry("500x400")
a=Label(window,text="name:")
a.grid(row=0,column=0)
e1=Entry(window)
e1.grid(row=0,column=1)
b=Label(window,text="password:")
b.grid(row=1,column=0)
e2=Entry(window)
e2.grid(row=1,column=1)
btn1=Button(window,text="Submit")
btn1.grid(row=3,column=1)
window.mainloop()