from tkinter import *
top = Tk()
top.title("Welcome")
top.geometry("300x200")
l1 = Label(top,text="Username:")
l1.grid(row=0,column=0,padx=10,pady=5)
e1 =Entry(top)
e1.grid(row=0,column=1)
regno = Label(top,text="Regno:")
regno.grid(row=1,column=0,padx=10,pady=5)
e2 = Entry(top)
e2.grid(row=1,column=1)
btn = Button(top,text="Click me")
btn.grid(row=2,column=1)
top.mainloop()